### ISSUE TITLE
Where to do npm run auth?

### ISSUE THREAD

**Issue by bjorndegroot** [Fabrizz/MMM-OnSpotify#12]
After I did those steps:

cd ~/MagicMirror/modules
git clone https://github.com/Fabrizz/MMM-OnSpotify.git
cd MMM-OnSpotify
npm install

I don't really understand where to run "npm run auth".
When I do this in the folder MMM-OnSpotify I get the following error message and in the Auth folder it doesn't work also:

pi@raspberrypi:~/MagicMirror/modules/MMM-OnSpotify $ npm run auth
npm ERR! Missing script: "auth"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-04-15T23_01_44_670Z-debug-0.log

Does anybody know how to configure this?

**Comment by bjorndegroot** [comment]
Seems to work after a reboot.

**Comment by Fabrizz** [comment]
Sorry for the late response, does it work now?

**Comment by DarkPlayerr** [comment]
i had a similar issue!
after installing mmm-onspotify from mmm-nowplayingonspotify, the widget showed, but didn't work (kept saying connecting to spotify or something like that). i wanted to make the auth keys again, but npm run auth did not work. a pc restart fixed it (without making new keys, reusing the mmm-nowplayingonspotify keys)

probably should note that in the readme, but besides that the module works great! <3
