### ISSUE TITLE
MMM-OnSpotify stuck on load

### ISSUE THREAD

**Issue by loriemrq** [Fabrizz/MMM-OnSpotify#13]
Hi,

I just finished the configuration of the OnSpotify module but when I restart the Magic Mirror, the module can't connect to Spotify and is stuck on load. What is writtent is "Connecting to Spotify...". 

My config file is exactly the same as in the README, I simply added the keys and IDs to my Spotify App. 

I'm very new to this and have very limited knowledge, so please try not to go too much into details in your answer. 

Thank you in advance for your help. 

![image](https://user-images.githubusercontent.com/132444887/235879775-b77fffa1-3693-4563-abaa-50251d92afb2.png)

**Comment by Fabrizz** [comment]
Hi!, can you provide a screenshot of the logs in the mirror? You can access them by opening the dev tools, pressing F12 or SHIFT+I. Is your account sp premium?

**Comment by Fabrizz** [comment]
Hey did you migrate from NowPlayingInSpotify? I just realized that you cannot migrate credentials from the other module (as the credentials generated by NPOS do not include user based scopes)

**Comment by loriemrq** [comment]
Hi ! Thank you very much for your answer !
