### ISSUE TITLE
feature request: album cover resizing

### ISSUE THREAD

**Issue by DarkPlayerr** [Fabrizz/MMM-OnSpotify#14]
i installed mmm-onspotify and it works great, but i find the album cover a bit too big (although that could just be my 768p display)
would love to see an option to make it smaller (small, medium, large perhaps?)

the medium one could be the width of the spotify bar code, as right now there's a wide padding on the sides, maybe the medium size album cover would be the width of the bar code with all of it's paddings (top/bottom/left/right) matching?

i made a quick concept to visualize it:
![Frame 251](https://github.com/Fabrizz/MMM-OnSpotify/assets/22507352/88be6f1b-f37f-49c0-941e-3378ac570345)

also, it would be cool, if it was possible to hide the pipe thing that's on the left of the song title/artist

**Comment by Fabrizz** [comment]
Hey, im going t oadd an option to remove the pipe thing, about the sizing you can change the font size that calculates everything else:
```css
.ONSP-Custom {
  font-size: 16px;  /* Font size controls all the relative sizings */
}
```
If that does not work let me know.

Also did you have any problems with a white background? I did not know people used that, but for non mirror displays I imagine it would look nice

**Comment by Fabrizz** [comment]
Just added the pipe hide option! also fixed LiveLyrics

**Comment by DarkPlayerr** [comment]
> Hey, im going t oadd an option to remove the pipe thing, about the sizing you can change the font size that calculates everything else:
> ```css
> .ONSP-Custom {
>   font-size: 16px;  /* Font size controls all the relative sizings */
> }
> ```
> If that does not work let me know.
> 
> Also did you have any problems with a white background? I did not know people used that, but for non mirror displays I imagine it would look nice

oh, it's a figma concept i made quick to visualize it, not my actual setup 😅

thanks for adding the change, appreciate it! ❤️

**Comment by DarkPlayerr** [comment]
i noticed some scaling/padding issues with the smaller font but it's no biggie

this is how the no music playing screen looks by default
![Screenshot at 2023-05-18 00-15-33~2.png](https://github.com/Fabrizz/MMM-OnSpotify/assets/22507352/a4d9f62b-173f-4cfe-8c38-a2a3edbaaf0f)

and this is how it looks after being rescaled to 22px (i think)
![Screenshot at 2023-05-18 00-16-55~2.png](https://github.com/Fabrizz/MMM-OnSpotify/assets/22507352/2854ef67-d68b-4af6-a8e9-70c2a306b308)

**Comment by DarkPlayerr** [comment]
just updated mmm-onspotify, but the custom css for the smaller font stopped working. i saw the implementation being changed and besides 
```
.ONSP-Custom {
  font-size: 16px;  /* Font size controls all the relative sizings */
}
```
in my css/custom.css i've toggled experimentalCSSOverridesForMM2: true in my config.js to no avail.

am i missing anything?

**Comment by Fabrizz** [comment]
Thats strange, as the last version does not add/removes/changes any of the theming/css parts, just adds device filtering. I would add the custom CSS to the custom.css file of MM2, not te module by itself, also I would add an !important so it has priority.

**Comment by Fabrizz** [comment]
`experimentalCSSOverridesForMM2` is for applying color to other modules, it accepts an array. Readme has a couple of examples

**Comment by DarkPlayerr** [comment]
> Thats strange, as the last version does not add/removes/changes any of the theming/css parts, just adds device filtering. I would add the custom CSS to the custom.css file of MM2, not te module by itself, also I would add an !important so it has priority.
> 
> 

i haven't updated my modules in ages, so it might've been the issue. anyways, !important in the mm2 css worked great, thanks.
