### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by EmmanuelZapata** [Fabrizz/MMM-OnSpotify#17]
Hello!  Is it possible to have multiple accounts setup?  So that if my partner is on her phone playing some music it shows up?  I added her email to the list but I'm not seeing anything. 

Thanks!

**Comment by Fabrizz** [comment]
> Hello!  Is it possible to have multiple accounts setup?  So that if my partner is on her phone playing some music it shows up?  I added her email to the list but I'm not seeing anything. 
> 
> Thanks!

Hi, currently there is no way to use multiple account in the same module, I don't know if there are other module that allow you to spin up different instances of the same module.

If it's a requested feature I'm happy to add it, but currently I don't have time.
