### ISSUE TITLE
Option to disable progress bar and track length / track progress

### ISSUE THREAD

**Issue by hannesknutsson** [Fabrizz/MMM-OnSpotify#21]
Hi,

It would be great to be able to disable the progress bar and all the text below it completely. I am working with a rather small screen, so any real estate I can gain by taking up less space is worth a lot.

Thanks for a great module! :)

**Comment by Fabrizz** [comment]
An option for that would be a good addition, when I have time im going to do it, for now you can probably use a custom CSS class that disables that part (using `display: none`)
