### ISSUE TITLE
Cant Remove Blur Backround

### ISSUE THREAD

**Issue by FassRoller** [Fabrizz/MMM-OnSpotify#23]
I have edited the MMM-OnSpotify.js and set showBlurBackground to false nevertheless the blur backround remains. I also did Disabling all color theming (according to the instructions) but the blur background still remains.

**Comment by Fabrizz** [comment]
You need to put `showBlurBackground: false` inside the config part of the module. I cannot recreate the issue. If you send your config maybe I can help you a little more
