### ISSUE TITLE
Spotify through Sonos app?

### ISSUE THREAD

**Issue by round-nearest** [Fabrizz/MMM-OnSpotify#34]
Fantastic module you have developed here!  So cool!

My family and I usually play our Spotify account through our Sonos app.  Unfortunately, when we do that, the module doesn't seem to work.  The module says nothing is playing.

If I start playing music through the Spotify app and send the output to Sonos, then it works.

But if I use the Sonos app to play Spotify, it does not.  We are 100% sure it is using the correct Spotify account, we're just using the Sonos app as the front end to access it.

The way we use our home system, the Sonos app works better for our family's use cases.

Any thoughts or tips?  Could this still work?

**Comment by Fabrizz** [comment]
I thought that Sonos always reported to Spotify when playback started, I guess it only does that when its started from the app.

The only way to circumvent this would be to change the `SpotifyFetcher.js` helper to also get status from a local sonos system. (maybe using https://github.com/jishi/node-sonos-http-api, and then normalizing the data so its like the spotify api response)

I dont have a sonos device right now so I can not test it.
