### ISSUE TITLE
Cant change any settings.

### ISSUE THREAD

**Issue by WilliamFredriksson1** [Fabrizz/MMM-OnSpotify#37]
Great job developing this module, it is amazing.

But I have a problem where I cant change any settings, when I put anything under the tokens I get errors saying the configurations contains syntax errors. Do you have any idea why this is? to be safe I coppied some configs directly from your "read me" file.

Best regards,
William.

**Comment by Fabrizz** [comment]
Hi, thanks! That is strange, can you send me the config that you are currently using/that you want to change? maybe there is a little error or something is wrong with the install. Also check the logs maybe there is something there.

Clean installing MM2 sometimes helps, idk why but updating multiple times MM2 has a higher chance of the install being buggy.
