### ISSUE TITLE
Feature Request: Specific Device

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-OnSpotify#39]
Hi again. I use Spotify to listen to music and I have Amazon Echoes in multiple rooms, however, my MagicMirror is in the Kitchen, where I also have an echo. It's not very convenient seeing what's playing in a different room on a mirror in the kitchen. Is it possible to add a feature to only show what's playing on a specific device?

**Comment by Fabrizz** [comment]
Will look into this!

**Comment by Fabrizz** [comment]
V3.2.0 adds this!

**Comment by TheEpicTen** [comment]
Not working...


Not sure if I've updated, don't know how to do it really or how to tell.

**Comment by Fabrizz** [comment]
To update the module, in the module folder (`modules/MMM-OnSpotify`), you need to run:
```bash
git pull
npm install
```
Then you can view the version: vX.X.X in the `package.json` file.

**Comment by TheEpicTen** [comment]
Done, thanks!
