### ISSUE TITLE
header still visible when not playing

### ISSUE THREAD

**Issue by greedyvegan** [Fabrizz/MMM-OnSpotify#58]
2 things:
1 -  displayWhenEmpty: "none", but header is visible and so is the white background.
<img width="370" alt="Screenshot 2024-03-19 at 11 38 44 AM" src="https://github.com/Fabrizz/MMM-OnSpotify/assets/128918275/5f34428a-be13-4a25-8491-1ddf00b85f2e">

2 - the header is "ABOVE" the module by a LOT, but not on other modules.
<img width="163" alt="Screenshot 2024-03-19 at 11 41 31 AM" src="https://github.com/Fabrizz/MMM-OnSpotify/assets/128918275/d226c9bb-ec73-474e-a2ad-44b9adc5d3ca">

please help, thank you.

**Comment by Fabrizz** [comment]
Hi, what UI are you using for MM²? That does not look native.

But you are right, the module just appends some comments signaling that it's hidden on the HTML, I will add an option to hide the module natively to MM²

**Comment by greedyvegan** [comment]
- the layout number 6 (White Boxes)
https://forum.magicmirror.builders/topic/13108/css-experiments-for-newbies/3

**Comment by greedyvegan** [comment]
here's the whole layout
spotify goes under the wifi code, but it's not playing right now
I haven't occupied the rest of the empty spots.
my photos and news modules aren't running because I kept refreshing to modify the code and depleted the api
<img width="685" alt="Screenshot 2024-03-20 at 3 22 07 PM" src="https://github.com/Fabrizz/MMM-OnSpotify/assets/128918275/71046b78-0aa9-4630-bcc8-3a95dd268857">

**Comment by Fabrizz** [comment]
Are you setting a `header:` in the config file?, it seems that that theme sets a white background to the module, maybe you could override that for this module in the css, and set the white background inside this module's css, so that white background only appears with the module.

**Comment by greedyvegan** [comment]
copy, thank you.
