### ISSUE TITLE
Hi again. How to use Dynamic Theme?

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-OnSpotify#6]
I need dynamic theming, but I don't know where to put this:

`{ /* Playing */
    provider: "MMM-OnSpotify",
    providerPrefix: "ONSP",
    providerScheme: "VIBRANT",
    // CSS VARS: --(ONSP)-(VIBRANT)-(VIBRANT-SCHEME-COLOR]
    set: "lock",
    until: "provider",
    priority: true,
    // Lock on [MMM-OnSpotify] until [provider] decides (player is empty)
}

{ /* Player empty */
    provider: "MMM-OnSpotify",
    set: "unlock",
}`

**Comment by Fabrizz** [comment]
Dynamic theme is **just a scheme** for modules to know where to listen for color data. None of my modules are updated yet as im finishing rewriting again [MMM-LiveLyrics](https://github.com/Fabrizz/MMM-LiveLyrics), the next update of **OnSpotify** enables the connection with **LiveLyrics**, Im working in a viewport calculator so the module is not just a background or a overlay. If I have time maybe this week its finished.

The module to theme the default modules using Dynamic Theme is not even started yet.
