### ISSUE TITLE
Vulkan error, User shown but nothing is playing

### ISSUE THREAD

**Issue by tttjones** [Fabrizz/MMM-OnSpotify#60]
I followed the readme, I installed everything cleanly on a new Raspbian OS image. I keep getting this error, when MagicMirror starts (this is the pm2 logs):
`0|MagicMir | > magicmirror@2.26.0 start
0|MagicMir | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|MagicMir |

0|MagicMirror  | [24.03.2024 16:18.50.976] [LOG]   Starting MagicMirror: v2.26.0
0|MagicMirror  | [24.03.2024 16:18.50.991] [LOG]   Loading config ...
0|MagicMirror  | [24.03.2024 16:18.51.004] [DEBUG] config template file not exists, no envsubst
0|MagicMirror  | [24.03.2024 16:18.51.018] [LOG]   Loading module helpers ...
0|MagicMirror  | [24.03.2024 16:18.51.231] [LOG]   Initializing new module helper ...
0|MagicMirror  | [24.03.2024 16:18.51.234] [LOG]   Module helper loaded: MMM-OnSpotify
0|MagicMirror  | [24.03.2024 16:18.51.236] [LOG]   All module helpers loaded.
0|MagicMirror  | [24.03.2024 16:18.51.261] [LOG]   Starting server on port 8080 ...
0|MagicMirror  | [24.03.2024 16:18.51.273] [WARN]  You're using a full whitelist configuration to allow for all IPs
0|MagicMirror  | [24.03.2024 16:18.51.342] [LOG]   Server started ...
0|MagicMirror  | [24.03.2024 16:18.51.345] [LOG]   Connecting socket for: MMM-OnSpotify
0|MagicMirror  | [24.03.2024 16:18.51.348] [LOG]   [Node Helper] Init >> MMM-OnSpotify
0|MagicMirror  | [24.03.2024 16:18.51.350] [LOG]   Sockets connected & modules started ...
0|MagicMirror  | [24.03.2024 16:18.51.907] [LOG]   Launching application.
0|MagicMirror  | Warning: vkCreateInstance: Found no drivers!
0|MagicMirror  | Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
0|MagicMirror  |     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
0|MagicMirror  |     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
0|MagicMirror  |     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
0|MagicMirror  |     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
0|MagicMirror  |     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)
`

Meanwhile MagicMirror displays the 9 album covers, my username and "Nothing is playing" (even if I am playing something). I tried redoing the auth process several times without success. My credentials seem to be fine as I also get a token back using `curl -X POST "https://accounts.spotify.com/api/token"      -H "Content-Type: application/x-www-form-urlencoded"      -d "grant_type=client_credentials&client_id=<id>&client_secret=<secret>"`

I have also added the Lyrics module, which then is able to get the currently playing song, but it only gets it once upon starting it. Then that song + lyrics just stays the same without moving by section.

Any ideas?

**Comment by Fabrizz** [comment]
Hey, this is definitely new, do you see any errors on the frontend (electron app)? (`F12` to open devtools)

it seems that maybe its has a problem with the VIbrant lib color processing. The fact that the song appears on the lyrics module is good, as it means its just a frontend thing

**Comment by Fabrizz** [comment]
Edit > Its a fairly recent bug https://forum.magicmirror.builders/topic/18410/vkcreateinstance-failed-with-found-no-drivers, but its not related to the module not displaying correctly, you should be able to ignore that error.

**Comment by tttjones** [comment]
I get this error in the dev tools:
Refused to apply style from 'http://localhost:8080/css/cust localhost/:1om.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Error on loading stylesheet: css/custom.css                     loader.js:190

**Comment by Fabrizz** [comment]
I read a bit in the forum and it seems that the vulkan error is just something raised but it just continues. About the module not showing, are there any logs in MM2? If you are using PM2 you can use `pm2 logs` if I remember correctly

**Comment by tttjones** [comment]
I have let it sit 2 hours, and the 'pm2 logs' don't display anything else than what I posted initially in this issue.

The dev tools on the Raspberry Pi display the errors in this image. The last two appeared when I played something on Spotify (probably the second one as well, I just didn't have the tools open earlier).
![IMG_1101](https://github.com/Fabrizz/MMM-OnSpotify/assets/164775465/cc7ad71b-a2fc-420b-bb1d-3ede946dbcca)

**Comment by Fabrizz** [comment]
Sorry, I did not saw this. It seems to be an error with moment, an issue that some users already had. The next update will remove this dependencies that collide with mm2 included ones.

I will also look at that style, null issue there, thanks
