### ISSUE TITLE
Module not hiding upon no playback on device

### ISSUE THREAD

**Issue by glucaz** [Fabrizz/MMM-OnSpotify#7]
The module does not hide the player/revert back to the default stance stated in the "displayWhenEmpty" field when playback stops and the spotify application is closed on any device. The old version of the player used to do this.

**Comment by Fabrizz** [comment]
Can you share your config / what `displayWhenEmpty` setting are you using? Some devices do not tell Spotify when the session is closed (Ex: a web playback).

This is what should happen:

https://user-images.githubusercontent.com/65259076/227662249-8fdc9eae-6380-44f1-aac2-3282765529d0.mp4

(Salir = Exit)
