### ISSUE TITLE
Problem (see first link)

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-OnSpotify#76]
https://github.com/MagicMirrorOrg/MagicMirror/issues/3409

Since this problem only appears when something is playing on this module, I'm moving the issue to here. Anyone know why this is happening?

**Comment by Fabrizz** [comment]
Hey, this is an issue with how chromium renders things. I dont know if you are using electron or just the server, if you are using electron im sure that some flags can be changed to configure how it renders things
