### ISSUE TITLE
Notification Payload not correct

### ISSUE THREAD

**Issue by martbrad11** [Fabrizz/MMM-OnSpotify#77]
I'm trying to use the Notifications to run in a script.
I can see the NOW_PLAYING notification but it's payload is always '[Object'
Can you help me understand why, I expected a song ID

**Comment by Fabrizz** [comment]
Hey, are you stringifying the response?

https://github.com/Fabrizz/MMM-OnSpotify/blob/77af57cef839dc7a5ad457f75ca99ea73a9dba93/MMM-OnSpotify.js#L349-L362

The data sent seems to be correct. Are you listening when the song changes or are you sending a `GET_PLAYING` notification?

**Comment by martbrad11** [comment]
I was listening when the song changes, not sure if I was "stringifying" the response. Moved on now and decided to do my project another way outside MagicMirror
Thanks
