### ISSUE TITLE
Canvas not showing

### ISSUE THREAD

**Issue by lazy-senior** [Fabrizz/MMM-OnSpotify#79]
Im trying to use the canvas feature, but the canvas is not showing.
I see the following entry in the log:
`[CANVAS DATA] {"canvasesList":[]} undefined`

Tried several songs that have a canvas in the app.
My config is the basic config with only the mmm-onspotify module active with this configuration:
```
modules: [
		{
			/* Don't share your credentials! */
			module: "MMM-OnSpotify",
			position: "bottom_right", /* bottom_left, bottom_center */
				config: {
				clientID: "...",
				clientSecret: "...",
				accessToken: "...",
				refreshToken: "...",
				/* Add here your theming and behaviour configurations */
				experimentalCanvas: true,
        		
			},
		},
	]
```

**Comment by Fabrizz** [comment]
Hi, I marked it as expermiental becaouse Spotify really does not like people using their internal tools, different from the Spotify Code that its from a CDN, canvases, lyrics and other stuff like color data (that why the module has to do the extraction) gets blocked really easily. Still, I will look into it as it looks great.

**Comment by Marv1896** [comment]
Is this the same error I´ll receive after "npm run config:check" --> [ERROR] cover is not defined ? Or do I have a wrong configuration? Without these line its working.

**Comment by Fabrizz** [comment]
> Is this the same error I´ll receive after "npm run config:check" --> [ERROR] cover is not defined ? Or do I have a wrong configuration? Without these line its working.

Can you share you config?
The only place where cover should be is here `experimentalCanvasEffect: "cover",`, and it should be between single or double quotes (Its a string!)

**Comment by Fabrizz** [comment]
> Im trying to use the canvas feature, but the canvas is not showing. I see the following entry in the log: `[CANVAS DATA] {"canvasesList":[]} undefined`
> 
> Tried several songs that have a canvas in the app. My config is the basic config with only the mmm-onspotify module active with this configuration:
> 
> ```
> modules: [
> 		{
> 			/* Don't share your credentials! */
> 			module: "MMM-OnSpotify",
> 			position: "bottom_right", /* bottom_left, bottom_center */
> 				config: {
> 				clientID: "...",
> 				clientSecret: "...",
> 				accessToken: "...",
> 				refreshToken: "...",
> 				/* Add here your theming and behaviour configurations */
> 				experimentalCanvas: true,
>         		
> 			},
> 		},
> 	]
> ```

Im about to push an update that allows you to add a Spotify Web cookie to auth with the canvas, at least for me this works perfectly

**Comment by Marv1896** [comment]
> > Is this the same error I´ll receive after "npm run config:check" --> [ERROR] cover is not defined ? Or do I have a wrong configuration? Without these line its working.
> 
> Can you share you config? The only place where cover should be is here `experimentalCanvasEffect: "cover",`, and it should be between single or double quotes (Its a string!)

Ahh. Thanks. My mistake. Long day. Will check that tomorrow.

**Comment by lazy-senior** [comment]
> > Im trying to use the canvas feature, but the canvas is not showing. I see the following entry in the log: `[CANVAS DATA] {"canvasesList":[]} undefined`
> > Tried several songs that have a canvas in the app. My config is the basic config with only the mmm-onspotify module active with this configuration:
> > ```
> > modules: [
> > 		{
> > 			/* Don't share your credentials! */
> > 			module: "MMM-OnSpotify",
> > 			position: "bottom_right", /* bottom_left, bottom_center */
> > 				config: {
> > 				clientID: "...",
> > 				clientSecret: "...",
> > 				accessToken: "...",
> > 				refreshToken: "...",
> > 				/* Add here your theming and behaviour configurations */
> > 				experimentalCanvas: true,
> >         		
> > 			},
> > 		},
> > 	]
> > ```
> 
> Im about to push an update that allows you to add a Spotify Web cookie to auth with the canvas, at least for me this works perfectly

Ill check it out today

**Comment by lazy-senior** [comment]
Works! When there is already a track running and magic mirror is started, the canvas is not showing. But after switching to a new track then it works all the time.

**Comment by WallysWellies** [comment]
Would it be possible to slightly elaborate on the requirements for this one?

I have extracted the content of the "sp_dc" cookie from my browser and added it to the config. It's a 210 character string. Is this the correct data? I'm not having much luck getting it to work.

**Comment by Fabrizz** [comment]
Yes its the correct cookie, but some weeks ago spotify changed the auth methods for some APIs and now stuff like canvas/lyrics returns a message explicitly saying that the use breaks their TOS. (This was probably done due to scrapping content to train ai models etc, also, it is/was an issue for nearly all open source projects that used something like librespot)

Im updating the module to remove this feature, im not against having the feature, but I cannot update the module every time Spotify changes something.

**Comment by WallysWellies** [comment]
Ah fair enough. That's a shame as it was a great feature but understandable. Thanks for the info and cheers for the great module.
